In [20]:
# 4.1 数据类型
## 4.1.1 数值 数值 类型
import tensorflow as tf
print("==============4.1.1 数值 数值 类型==============")
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(a.shape)

## 4.1.2 字符串类型
print("==============4.1.2 字符串类型==============")
b = tf.constant('HELLO, Deep Learning.')# 实例化一个字符串变量
b=tf.strings.lower(b) # 将所有字母变为小写
print(b)
## 4.1.3 布尔类型
print("==============4.1.3 布尔类型==============")
c= tf.constant(True)
print(c)
c = tf.constant([True, False])
print(c)
### TensorFlow 的布尔类型和 Python 语言的布尔类型并不对等，不能通用
c = tf.constant(True) # 创建布尔张量
print(c==True)

==============4.1.1 数值 数值 类型==============
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
(2, 2, 2)
==============4.1.2 字符串类型==============
tf.Tensor(b'hello, deep learning.', shape=(), dtype=string)
==============4.1.3 布尔类型==============
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor([ True False], shape=(2,), dtype=bool)
tf.Tensor(True, shape=(), dtype=bool)


In [34]:
# 4.2 数值精度
import tensorflow as tf
import numpy as np
a=tf.constant(123456789, dtype=tf.int16)
a1=tf.constant(123456789, dtype=tf.int32)
print(a)
print(a1)
a2=tf.constant(np.pi, dtype=tf.float32)
a3=tf.constant(np.pi, dtype=tf.float64)
print(a2)
print(a3)
## 4.2.1 读取精度
print('before:',a.dtype)
if a.dtype != tf.float32:
    a = tf.cast(a,tf.float32) # 转换精度
print('after :',a.dtype)
## 4.2.2 类型转换
a = tf.constant(np.pi, dtype=tf.float16)
a=tf.cast(a, tf.double)
print("a转double:{}".format(a.dtype))
### 进行类型转换时，需要保证转换操作的合法性，例如将高精度的张量转换为低精度的张量时，可能发生数据溢出隐患：
a=tf.constant(123456789,dtype=tf.int32)
a=tf.cast(a,tf.int16)
print("a有32转16位:",a)
### 布尔型与整形之间相互转换也是合法的，是比较常见的操作：
a = tf.constant([True, False])
a=tf.cast(a,tf.int32)
print("布尔型与整形之间相互转换：",a)
### 一般默认 0 表示 False，1 表示 True，在 TensorFlow 中，将非 0 数字都视为 True
a = tf.constant([-1, 0, 1, 2])
a=tf.cast(a, tf.bool)
print("整型转bool类型：",a)


tf.Tensor(-13035, shape=(), dtype=int16)
tf.Tensor(123456789, shape=(), dtype=int32)
tf.Tensor(3.1415927, shape=(), dtype=float32)
tf.Tensor(3.141592653589793, shape=(), dtype=float64)
before: <dtype: 'int16'>
after : <dtype: 'float32'>
a转double:<dtype: 'float64'>
a有32转16位: tf.Tensor(-13035, shape=(), dtype=int16)
布尔型与整形之间相互转换： tf.Tensor([1 0], shape=(2,), dtype=int32)
整型转bool类型： tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [38]:
# 4.3 待优化张量
### 张量的 name 和 trainable 属性是 Variable 特有的属性，
### name 属性用于命名计算图中的变量，这套命名体系是 TensorFlow 内部维护的，一般不需要用户关注 name 属性；
### trainable表征当前张量是否需要被优化，创建 Variable 对象是默认启用优化标志，可以设置trainable=False 来设置张量不需要优化。
a=tf.constant([-1,0,1,2])
aa=tf.Variable(a)
print(aa)
print(aa.name)
print(aa.trainable)
### 除了通过普通张量方式创建 Variable，也可以直接创建：
b = tf.Variable([[1,2],[3,4]])
print("b",b)
### 待优化张量可看做普通张量的特殊类型，普通张量也可以通过 GradientTape.watch()方法临时加入跟踪梯度信息的列表。

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([-1,  0,  1,  2])>
Variable:0
True
b <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>


In [65]:
# 4.4 创建张量
### Numpy Array 数组和 Python List 是 Python 程序中间非常重要的数据载体容器
### 很多数据都是通过 Python 语言将数据加载至 Array 或者 List 容器，再转换到 Tensor 类型
### 通过TensorFlow 运算处理后导出到 Array 或者 List 容器，方便其他模块调用。
## 4.4.1 从 从 Numpy, List 对象 创建
### 通过 tf.convert_to_tensor 可以创建新 Tensor，并将保存在 Python List 对象或者 NumpyArray 对象中的数据导入到新 Tensor 中
a=tf.convert_to_tensor([1,2.])
### 需要注意的是，Numpy 中浮点数数组默认使用 64-Bit 精度保存数据，
### 转换到 Tensor 类型时精度为 tf.float64，可以在需要的时候转换为 tf.float32 类型。
aa=tf.convert_to_tensor(np.array([[1,2.],[3,4]]))
print("a:",a)
print("aa:",aa)
## 4.4.2 创建全 全 0 ，全 1 张量
b=tf.zeros([])
b1=tf.ones([])
b2=tf.ones([1])
b3=tf.zeros([1])
print("b:",b)
print("b1",b1)
print("b2",b2)
print("b3",b3)
# 创建全 0 的矩阵：
b4=tf.zeros([2,3])
print("b4",b4)
# 创建全1矩阵
b5=tf.ones([6,6])
print("b5",b5)
### 过 tf.zeros_like, tf.ones_like 可以方便地新建与某个张量 shape 一致，内容全 0 或全 1的张量。
### 例如，创建与张量 b6 形状一样的全 0 张量：
b6=tf.ones([2,3])
b7=tf.zeros_like(b6)
print("b7",b7)
    ## 4.4.3 创建 创建 自定义数值
### 除了初始化为全 0，或全 1 的张量之外，有时也需要全部初始化为某个自定义数值的张量，比如将张量的数值全部初始化为-1 等。
### 通过 tf.fill(shape, value)可以创建全为自定义数值 value 的张量。例如，创建元素为-1的标量：
c=tf.fill([3,4],-1)
print("C:",c)
## 4.4.4 创建已知分布的张量
### 正态分布(Normal Distribution，或 Gaussian Distribution)
### 均匀分布(UniformDistribution)是最常见的分布之一，创建采样自这 2 种分布的张量非常有用
### 比如在卷积神经网络中，卷积核张量 W 初始化为正态分布有利于网络的训练；
### 在对抗生成网络中，隐藏变量 z 一般采样自均匀分布。
### 通过 tf.random.normal(shape, mean=0.0, stddev=1.0)可以创建
### 形状为 shape，均值为mean,标准差为 stddev 的正态分布𝒩(𝑛𝑓𝑏𝑜,𝑡𝑢𝑒𝑒𝑓𝑤 2 )。
### 下面创建一个均值为0，标准差为1的正态分布
d=tf.random.normal([2,2])
print("d:",d)
### 创建均值为 1，标准差为 2 的正太分布：
d1=tf.random.normal([2,2], mean=1,stddev=2)
print("d1",d1)
### 通过 tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.float32)可以创建采样自[𝑛𝑗𝑜𝑤𝑏𝑚,𝑛𝑏𝑦𝑤𝑏𝑚]区间的均匀分布的张量。
### 例如创建采样自区间[0,1]，shape 为[2,2]的矩阵：
d2=tf.random.uniform([2,2])
print("d2",d2)
### 创建采样自区间[0,10]，shape 为[2,2]的矩阵：
d3=tf.random.uniform([2,2],maxval=10)
print("d3",d3)
### 如果需要均匀采样整形类型的数据，必须指定采样区间的最大值 maxval 参数，同时制定数据类型为 tf.int*型：
d4=tf.random.uniform([2,2],maxval=100,dtype=tf.int32)
print("d4",d4)
## 4.4.5 创建序列
### 在循环计算或者对张量进行索引时，经常需要创建一段连续的整形序列
### 可以通过tf.range()函数实现。
### tf.range(limit, delta=1)可以创建[0,𝑚𝑗𝑛𝑗𝑢)之间，步长为 delta 的整形序列，不包含 limit 本身。例如，创建 0~9，步长为 1 的整形序列
e=tf.range(10,delta=1)
print("e",e)
### 创建 0~9，步长为 2 的整形序列：
e1=tf.range(10,delta=2)
print("e1",e1)
### tf.range(start, limit, delta=1)可以创建[𝑡𝑢𝑏𝑠𝑢,𝑚𝑗𝑛𝑗𝑢)，步长为 delta 的序列，不包含 limit本身：
e2=tf.range(1,limit=10,delta=1)
print("e2",e2)

a: tf.Tensor([1. 2.], shape=(2,), dtype=float32)
aa: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)
b: tf.Tensor(0.0, shape=(), dtype=float32)
b1 tf.Tensor(1.0, shape=(), dtype=float32)
b2 tf.Tensor([1.], shape=(1,), dtype=float32)
b3 tf.Tensor([0.], shape=(1,), dtype=float32)
b4 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
b5 tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(6, 6), dtype=float32)
b7 tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
C: tf.Tensor(
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]], shape=(3, 4), dtype=int32)
d: tf.Tensor(
[[-1.1901563   0.21974714]
 [ 0.06932668  0.40315804]], shape=(2, 2), dtype=float32)
d1 tf.Tensor(
[[-0.10858321  0.12188458]
 [ 2.537197    4.51826   ]], shape=(2, 2), dtype=float32)
d2 tf.Tensor(
[[0.92485726 0.1894319 ]
 [0.724565   0.32994676]], shape=(2, 2), dtype=float32)
d3 tf.Tensor(
[[7.8