In [7]:
import tensorflow as tf
# 保证sess.run()能够正常运行
tf.compat.v1.disable_eager_execution()
mat0=tf.constant([[0,0,0],[0,0,0]])# 定义一个2*3的空矩阵
mat1=tf.zeros([2,3])# 定义一个2*3的空矩阵
mat2=tf.ones([3,2])#定义一个3*2的全1矩阵
mat3=tf.fill([2,3],15)# 定义一个2*3的填充矩阵，填充内容为15
with tf.compat.v1.Session() as sess:
    print("全0矩阵：",sess.run(mat1))
    print("全1矩阵：",sess.run(mat2))
    print("填充矩阵：",sess.run(mat3))

全0矩阵： [[0. 0. 0.]
 [0. 0. 0.]]
全1矩阵： [[1. 1.]
 [1. 1.]
 [1. 1.]]
填充矩阵： [[15 15 15]
 [15 15 15]]


In [17]:
import tensorflow as tf
# 保证sess.run()能够正常运行
tf.compat.v1.disable_eager_execution()
mat1=tf.constant([[2],[3],[4]])
mat2=tf.zeros_like(mat1)# 定义一个和mat1维度相同的全零矩阵
mat3=tf.linspace(0.0,2.0,11)#定义一个1*10 从1到2被均分为10份的矩阵
mat4=tf.compat.v1.random_uniform([2,3],-1,2)# 定义一个2*3的矩阵，矩阵内容为-1,2所产生的随机数
with tf.compat.v1.Session() as sess:
    print("mat2",sess.run(mat2))
    print("均分矩阵mat3:",sess.run(mat3))
    print("随机矩阵mat4:",sess.run(mat4))

mat2 [[0]
 [0]
 [0]]
均分矩阵mat3: [0.        0.2       0.4       0.6       0.8       1.        1.2
 1.4       1.6       1.8000001 2.       ]
随机矩阵mat4: [[-0.55731857 -0.117854   -0.7026707 ]
 [-0.38001597  0.73309827  0.99627984]]
