In [9]:
import numpy as np
data1=np.array([1,2,3,4,5])
print(data1)
data2=np.array([[1,2],[3,4]])
print(data2)
print("data1维度:",data1.shape)
print("data2维度:",data2.shape)
# 矩阵的修改与查找
data2[1,0]=5 #将矩阵2的第二行第一列的值修改为5
print("修改之后的2矩阵：",data2)
print("矩阵2第二行第2列的值:",data2[1,1])
# 基本运算
data3=np.ones([2,3])
print("data3*2:",data3*2)


[1 2 3 4 5]
[[1 2]
 [3 4]]
data1维度: (5,)
data2维度: (2, 2)
修改之后的2矩阵： [[1 2]
 [5 4]]
矩阵2第二行第2列的值: 4
data3*2: [[2. 2. 2.]
 [2. 2. 2.]]
